version:
  config: "1.0.0"

spring:
  data:
    mongodb:
      database: drl-he-ep-db
      uri: mongodb+srv://dbReadWriteUser:sn7SYqlBNfxXhm7O@dc1.d5hdy.mongodb.net

  jackson:
    default-property-inclusion: NON_NULL

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - refresh

logging:
  level:
    com.netflix: warn
